# docker-compose.yml
version: '3'
services:
  database:
    image: "postgis/postgis" # use latest official postgres version
    env_file:
    - .env.local # configure postgres
    volumes:
    - ./data/:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
    - "25432:5432"
