version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm build
            - run: npm test
            - run: npm package:lambda
            - run: npm push:lambda
            - run: npm deploy:lambda
workflows:
    build-and-test:
      jobs:
        - build-and-test